Repository cosmos/ibc, pull requests merged in 2019-05, with the labels that each got.

#74 ICS 23: Vector commitments
  docs/ibc/1_IBC_ARCHITECTURE.md
  docs/ibc/2_IBC_DESIGN_PRINCIPLES.md
  docs/ibc/3_IBC_TERMINOLOGY.md
  spec/ics-23-vector-commitments/README.md
Labels: category-ibc-core, ready-for-review, stage-draft

#81 Some example IBC usecases
  README.md
  docs/README.md
  ibc/1_IBC_ARCHITECTURE.md
  ibc/2_IBC_DESIGN_PRINCIPLES.md
  ibc/3_IBC_TERMINOLOGY.md
  ibc/4_IBC_USECASES.md
  ibc/README.md
Labels: brainstorming, meta, ready-for-review

#75 ICS 24: Host state machine requirements
  spec/ics-24-host-requirements/README.md
Labels: category-ibc-core, ready-for-review, stage-draft

#32 ICS 3: Connection Semantics
  .gitattributes
  Makefile
  README.md
  ibc/3_IBC_TERMINOLOGY.md
  spec/ics-3-connection-semantics/Makefile
  spec/ics-3-connection-semantics/README.md
  spec/ics-3-connection-semantics/state.png
  spec/ics-3-connection-semantics/state.tex
Labels: category-ibc-core, ready-for-review, stage-draft

#96 Autoformatting
  .circleci/config.yml
  Makefile
  README.md
  deps.png
  scripts/check_dependencies.py
  scripts/check_links.py
  scripts/check_syntax.sh
  spec/ics-18-relayer-algorithms/README.md
  spec/ics-24-host-requirements/README.md
  spec/ics-3-connection-semantics/README.md
Labels: meta, ready-for-review

#97 Add CI to check sections
  .circleci/config.yml
  Makefile
  scripts/check_sections.py
Labels: meta, ready-for-review

#98 Fix CI, a bit of cleanup
  scripts/check_links.py
  spec/ics-1-ics-standard/README.md
  spec/ics-18-relayer-algorithms/README.md
  spec/ics-23-vector-commitments/README.md
  spec/ics-24-host-requirements/README.md
  spec/ics-3-connection-semantics/README.md
Labels: ready-for-review

#20 ICS 2: Consensus Verification
  .gitignore
  scripts/check_sections.py
  spec/ics-2-consensus-verification/README.md
  spec/ics-2-consensus-verification/VERIFIER.md
  spec/ics-24-host-requirements/README.md
  spec/ics-3-connection-semantics/README.md
Labels: category-ibc-core, ready-for-review, stage-draft

#101 Fix README
  README.md
  deps.png
Labels: ready-for-review

#103 Syntax experimentation
  .circleci/config.yml
  deps.png
  scripts/check_dependencies.py
  scripts/check_syntax.sh
  scripts/tslint.json
  spec/ics-1-ics-standard/README.md
  spec/ics-18-relayer-algorithms/README.md
  spec/ics-2-consensus-verification/README.md
  spec/ics-2-consensus-verification/VERIFIER.md
  spec/ics-23-vector-commitments/README.md
  spec/ics-24-host-requirements/README.md
  spec/ics-3-connection-semantics/README.md
Labels: meta
